#!/bin/bash
#
# task1_script - Display the dimensions of all pictures in current directory
#
# usage: ./rename_pictures
#
# Nicolas Carbonara
# Antoine Leresche
# Samuel Roland

for image in lab04_raw_files/*.{jpg,png}
do
    dim=$(identify -format '%w_%h' $image)

	ext="${image#*.}"
	name="${image%.*}"
	name="${name%%_[0-9]*}"

	if [[ "${image}" != "${name}_${dim}.${ext}" ]]
	then
		cp ${image} "${name}_${dim}.${ext}"
	else
		echo "${image} already present, canceling copy."
	fi
done
