#!/bin/bash
#
# task1_script - Display the dimensions of all pictures in current directory
#
# usage: ./rename_pictures
#
# Nicolas Carbonara
# Antoine Leresche
# Samuel Roland

for image in lab04_raw_files/*.{jpg,png}
do
    dim=$(identify -format '%w_%h' $image)

	ext="${image#*.}"
	name="${image%.*}"
	# remove dimension from the name of the picture
	name="${name%%_[0-9]*}"

	new_name="${name}_${dim}.${ext}"
	if ! ls | grep -i "${new_name}"
	then
		cp ${image} "${new_name}"
	else
		echo "${image} already present, canceling copy."
	fi
done
