#!/bin/bash
#
# task1_script - Display the dimensions of all pictures in current directory
#
# usage: ./show_dimensions
#
# Nicolas Carbonara
# Antoine Leresche
# Samuel Roland

for image in lab04_raw_files/*.{jpg,png}; do
    result=$(identify -format "$image"': width: %w, height: %h' $image)
    echo "$result"
done
