#!/bin/bash
#
# Task 2 - Display the dimensions of all pictures in $SRC directory
#
# usage: Must be ran inside public_html with "../show_dimensions" or "bash ../show_dimensions"
#
# Nicolas Carbonara
# Antoine Leresche
# Samuel Roland

SRC=lab04_raw_files

for image in "$SRC"/*.{jpg,png}; do
    result=$(identify -format 'width: %w, height: %h' $image)
    echo "$image: $result"
done
