#!/bin/bash
#
# task1_script - Display the dimensions of all pictures in current directory
#
# usage: ./rename_pictures
#
# Nicolas Carbonara 2025-03-24

cd lab04_raw_files
for image in *.jpg *.png *.pdf
do
	ext="${image#*.}"
	if [ "${ext}" = "pdf" ] 
	then
		ext="jpg"
	fi

	name="${image%.*}"
	name="${name%%_thumb}"
	new_name="${name}_thumb.${ext}"

	# We create the new name of the picture and we search it in the
	# current dirrectory, if present, we do nothing
	if ! ls | grep -i "${new_name}"
	then
		convert -geometry 300 ${image}[0] ${new_name}
	else
		echo "${image}: thumbnail already present, canceling thumbnail cration."
	fi
done
